<?php
/** @var \Boundsoff\BrandNews\Block\Adminhtml\Marketplace $block */
/** @var \Magento\Framework\Escaper $escaper */
$modules = $block->getModuleInfoService()->getVersions();
$marketplaceUri = $block->getMarketplaceUri();
?>

<section class="brand-marketplace">
    <hr class="page-separator" />
    <div class="row row-gutter">
        <div class="col-m-5">
            <img
                    class="magento-marketplace-logo"
                    src="<?= $escaper->escapeUrl($block
                        ->getViewFileUrl('Boundsoff_BrandNews::marketplace/images/logo-black.svg')); ?>"
                    alt="Partner"/>
            <div class="content">
                <h2 class="page-sub-title">Boundsoff</h2>
                <p class="partner-description">
                    <?= $escaper->escapeHtml(__(
                        'Extensions and Themes are an essential component of the Magento Ecosystem. ' .
                        'Please visit the Magento Marketplace to see the latest innovations that developers have ' .
                        'created to enhance your Magento Store.'
                    )); ?>
                </p>
                <ul>
                    <?php foreach ($modules as $module): ?>
                        <li>
                            <?= $escaper->escapeHtml($module['version']) ?>
                            (<?= $escaper->escapeHtml($module['name']) ?>)
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php if ($block->getDataHelper()->isUriAvailable($marketplaceUri)): ?>
                    <a class="action-secondary" target="_blank"
                       href="<?= $escaper->escapeHtml($marketplaceUri) ?>">
                        <?= $escaper->escapeHtml(__('Marketplace')) ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
